export enum ActionTypes {
  GET_DOCTORS = 'GET_DOCTORS',
  GET_DOCTORS_STARTED = 'GET_DOCTORS_STARTED',
  GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS',
  GET_DOCTORS_ERROR = 'GET_DOCTORS_ERROR',
  SHOW_DOCTORS_BY_SPECIALITY = 'SHOW_DOCTORS_BY_SPECIALITY',
  SHOW_DOCTORS_BY_NAME = 'SHOW_DOCTORS_BY_NAME',
  IS_DOCTOR_BY_NAME = 'IS_DOCTOR_BY_NAME',
  CLEAR_FILTERS = 'CLEAR_FILTERS',
}
